name: Publish package to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: extractions/setup-just@v1

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1

    - name: Setup Deno
      uses: denoland/setup-deno@v1.1.2

    - name: Build
      run: npm run build

    - name: remove dist/ package for now
      run: rm dist/*.tgz

    - name: Update package version
      run: |
        tag="${{ github.ref }}"
        tag="${tag/refs\/tags\/v/}"
        npm version $tag --no-git-tag-version --no-commit-hooks

    - name: npm publish @extism/extism
      uses: JS-DevTools/npm-publish@v2.2.2
      with:
        token: ${{ secrets.NPM_TOKEN }}

    - name: Update package name
      run: |
        pkg="$(<package.json jq '.name = "extism"')"
        echo "$pkg" >package.json

    - name: npm publish extism
      uses: JS-DevTools/npm-publish@v2.2.2
      with:
        token: ${{ secrets.NPM_TOKEN }}
    
    - name: typedoc
      run: npx typedoc .\src\mod.ts
    
    - name: Deploy docs to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: docs
